/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegocioBusinessIdRouteImport } from './routes/negocio.$businessId'
import { Route as NegocioBusinessIdIndexRouteImport } from './routes/negocio.$businessId.index'
import { Route as NegocioBusinessIdProductosRouteImport } from './routes/negocio.$businessId.productos'
import { Route as NegocioBusinessIdMovimientosRouteImport } from './routes/negocio.$businessId.movimientos'
import { Route as NegocioBusinessIdImpuestosRouteImport } from './routes/negocio.$businessId.impuestos'
import { Route as NegocioBusinessIdFacturacionRouteImport } from './routes/negocio.$businessId.facturacion'
import { Route as NegocioBusinessIdBalanceRouteImport } from './routes/negocio.$businessId.balance'
import { Route as NegocioBusinessIdAsistenteRouteImport } from './routes/negocio.$businessId.asistente'
import { Route as NegocioBusinessIdAprenderRouteImport } from './routes/negocio.$businessId.aprender'
import { Route as NegocioBusinessIdAnalisisRouteImport } from './routes/negocio.$businessId.analisis'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioBusinessIdRoute = NegocioBusinessIdRouteImport.update({
  id: '/negocio/$businessId',
  path: '/negocio/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioBusinessIdIndexRoute = NegocioBusinessIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NegocioBusinessIdRoute,
} as any)
const NegocioBusinessIdProductosRoute =
  NegocioBusinessIdProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdMovimientosRoute =
  NegocioBusinessIdMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdImpuestosRoute =
  NegocioBusinessIdImpuestosRouteImport.update({
    id: '/impuestos',
    path: '/impuestos',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdFacturacionRoute =
  NegocioBusinessIdFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdBalanceRoute =
  NegocioBusinessIdBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdAsistenteRoute =
  NegocioBusinessIdAsistenteRouteImport.update({
    id: '/asistente',
    path: '/asistente',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdAprenderRoute =
  NegocioBusinessIdAprenderRouteImport.update({
    id: '/aprender',
    path: '/aprender',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)
const NegocioBusinessIdAnalisisRoute =
  NegocioBusinessIdAnalisisRouteImport.update({
    id: '/analisis',
    path: '/analisis',
    getParentRoute: () => NegocioBusinessIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$businessId': typeof NegocioBusinessIdRouteWithChildren
  '/negocio/$businessId/analisis': typeof NegocioBusinessIdAnalisisRoute
  '/negocio/$businessId/aprender': typeof NegocioBusinessIdAprenderRoute
  '/negocio/$businessId/asistente': typeof NegocioBusinessIdAsistenteRoute
  '/negocio/$businessId/balance': typeof NegocioBusinessIdBalanceRoute
  '/negocio/$businessId/facturacion': typeof NegocioBusinessIdFacturacionRoute
  '/negocio/$businessId/impuestos': typeof NegocioBusinessIdImpuestosRoute
  '/negocio/$businessId/movimientos': typeof NegocioBusinessIdMovimientosRoute
  '/negocio/$businessId/productos': typeof NegocioBusinessIdProductosRoute
  '/negocio/$businessId/': typeof NegocioBusinessIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$businessId/analisis': typeof NegocioBusinessIdAnalisisRoute
  '/negocio/$businessId/aprender': typeof NegocioBusinessIdAprenderRoute
  '/negocio/$businessId/asistente': typeof NegocioBusinessIdAsistenteRoute
  '/negocio/$businessId/balance': typeof NegocioBusinessIdBalanceRoute
  '/negocio/$businessId/facturacion': typeof NegocioBusinessIdFacturacionRoute
  '/negocio/$businessId/impuestos': typeof NegocioBusinessIdImpuestosRoute
  '/negocio/$businessId/movimientos': typeof NegocioBusinessIdMovimientosRoute
  '/negocio/$businessId/productos': typeof NegocioBusinessIdProductosRoute
  '/negocio/$businessId': typeof NegocioBusinessIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$businessId': typeof NegocioBusinessIdRouteWithChildren
  '/negocio/$businessId/analisis': typeof NegocioBusinessIdAnalisisRoute
  '/negocio/$businessId/aprender': typeof NegocioBusinessIdAprenderRoute
  '/negocio/$businessId/asistente': typeof NegocioBusinessIdAsistenteRoute
  '/negocio/$businessId/balance': typeof NegocioBusinessIdBalanceRoute
  '/negocio/$businessId/facturacion': typeof NegocioBusinessIdFacturacionRoute
  '/negocio/$businessId/impuestos': typeof NegocioBusinessIdImpuestosRoute
  '/negocio/$businessId/movimientos': typeof NegocioBusinessIdMovimientosRoute
  '/negocio/$businessId/productos': typeof NegocioBusinessIdProductosRoute
  '/negocio/$businessId/': typeof NegocioBusinessIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/negocio/$businessId'
    | '/negocio/$businessId/analisis'
    | '/negocio/$businessId/aprender'
    | '/negocio/$businessId/asistente'
    | '/negocio/$businessId/balance'
    | '/negocio/$businessId/facturacion'
    | '/negocio/$businessId/impuestos'
    | '/negocio/$businessId/movimientos'
    | '/negocio/$businessId/productos'
    | '/negocio/$businessId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/negocio/$businessId/analisis'
    | '/negocio/$businessId/aprender'
    | '/negocio/$businessId/asistente'
    | '/negocio/$businessId/balance'
    | '/negocio/$businessId/facturacion'
    | '/negocio/$businessId/impuestos'
    | '/negocio/$businessId/movimientos'
    | '/negocio/$businessId/productos'
    | '/negocio/$businessId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/negocio/$businessId'
    | '/negocio/$businessId/analisis'
    | '/negocio/$businessId/aprender'
    | '/negocio/$businessId/asistente'
    | '/negocio/$businessId/balance'
    | '/negocio/$businessId/facturacion'
    | '/negocio/$businessId/impuestos'
    | '/negocio/$businessId/movimientos'
    | '/negocio/$businessId/productos'
    | '/negocio/$businessId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  NegocioBusinessIdRoute: typeof NegocioBusinessIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$businessId': {
      id: '/negocio/$businessId'
      path: '/negocio/$businessId'
      fullPath: '/negocio/$businessId'
      preLoaderRoute: typeof NegocioBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$businessId/': {
      id: '/negocio/$businessId/'
      path: '/'
      fullPath: '/negocio/$businessId/'
      preLoaderRoute: typeof NegocioBusinessIdIndexRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/productos': {
      id: '/negocio/$businessId/productos'
      path: '/productos'
      fullPath: '/negocio/$businessId/productos'
      preLoaderRoute: typeof NegocioBusinessIdProductosRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/movimientos': {
      id: '/negocio/$businessId/movimientos'
      path: '/movimientos'
      fullPath: '/negocio/$businessId/movimientos'
      preLoaderRoute: typeof NegocioBusinessIdMovimientosRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/impuestos': {
      id: '/negocio/$businessId/impuestos'
      path: '/impuestos'
      fullPath: '/negocio/$businessId/impuestos'
      preLoaderRoute: typeof NegocioBusinessIdImpuestosRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/facturacion': {
      id: '/negocio/$businessId/facturacion'
      path: '/facturacion'
      fullPath: '/negocio/$businessId/facturacion'
      preLoaderRoute: typeof NegocioBusinessIdFacturacionRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/balance': {
      id: '/negocio/$businessId/balance'
      path: '/balance'
      fullPath: '/negocio/$businessId/balance'
      preLoaderRoute: typeof NegocioBusinessIdBalanceRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/asistente': {
      id: '/negocio/$businessId/asistente'
      path: '/asistente'
      fullPath: '/negocio/$businessId/asistente'
      preLoaderRoute: typeof NegocioBusinessIdAsistenteRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/aprender': {
      id: '/negocio/$businessId/aprender'
      path: '/aprender'
      fullPath: '/negocio/$businessId/aprender'
      preLoaderRoute: typeof NegocioBusinessIdAprenderRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
    '/negocio/$businessId/analisis': {
      id: '/negocio/$businessId/analisis'
      path: '/analisis'
      fullPath: '/negocio/$businessId/analisis'
      preLoaderRoute: typeof NegocioBusinessIdAnalisisRouteImport
      parentRoute: typeof NegocioBusinessIdRoute
    }
  }
}

interface NegocioBusinessIdRouteChildren {
  NegocioBusinessIdAnalisisRoute: typeof NegocioBusinessIdAnalisisRoute
  NegocioBusinessIdAprenderRoute: typeof NegocioBusinessIdAprenderRoute
  NegocioBusinessIdAsistenteRoute: typeof NegocioBusinessIdAsistenteRoute
  NegocioBusinessIdBalanceRoute: typeof NegocioBusinessIdBalanceRoute
  NegocioBusinessIdFacturacionRoute: typeof NegocioBusinessIdFacturacionRoute
  NegocioBusinessIdImpuestosRoute: typeof NegocioBusinessIdImpuestosRoute
  NegocioBusinessIdMovimientosRoute: typeof NegocioBusinessIdMovimientosRoute
  NegocioBusinessIdProductosRoute: typeof NegocioBusinessIdProductosRoute
  NegocioBusinessIdIndexRoute: typeof NegocioBusinessIdIndexRoute
}

const NegocioBusinessIdRouteChildren: NegocioBusinessIdRouteChildren = {
  NegocioBusinessIdAnalisisRoute: NegocioBusinessIdAnalisisRoute,
  NegocioBusinessIdAprenderRoute: NegocioBusinessIdAprenderRoute,
  NegocioBusinessIdAsistenteRoute: NegocioBusinessIdAsistenteRoute,
  NegocioBusinessIdBalanceRoute: NegocioBusinessIdBalanceRoute,
  NegocioBusinessIdFacturacionRoute: NegocioBusinessIdFacturacionRoute,
  NegocioBusinessIdImpuestosRoute: NegocioBusinessIdImpuestosRoute,
  NegocioBusinessIdMovimientosRoute: NegocioBusinessIdMovimientosRoute,
  NegocioBusinessIdProductosRoute: NegocioBusinessIdProductosRoute,
  NegocioBusinessIdIndexRoute: NegocioBusinessIdIndexRoute,
}

const NegocioBusinessIdRouteWithChildren =
  NegocioBusinessIdRoute._addFileChildren(NegocioBusinessIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  NegocioBusinessIdRoute: NegocioBusinessIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
