/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as ImpuestosRouteImport } from './routes/impuestos'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as IndexRouteImport } from './routes/index'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpuestosRoute = ImpuestosRouteImport.update({
  id: '/impuestos',
  path: '/impuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/aprender': typeof AprenderRoute
  '/facturacion': typeof FacturacionRoute
  '/impuestos': typeof ImpuestosRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/aprender': typeof AprenderRoute
  '/facturacion': typeof FacturacionRoute
  '/impuestos': typeof ImpuestosRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/aprender': typeof AprenderRoute
  '/facturacion': typeof FacturacionRoute
  '/impuestos': typeof ImpuestosRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/aprender'
    | '/facturacion'
    | '/impuestos'
    | '/movimientos'
    | '/productos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/aprender'
    | '/facturacion'
    | '/impuestos'
    | '/movimientos'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/aprender'
    | '/facturacion'
    | '/impuestos'
    | '/movimientos'
    | '/productos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  AprenderRoute: typeof AprenderRoute
  FacturacionRoute: typeof FacturacionRoute
  ImpuestosRoute: typeof ImpuestosRoute
  MovimientosRoute: typeof MovimientosRoute
  ProductosRoute: typeof ProductosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impuestos': {
      id: '/impuestos'
      path: '/impuestos'
      fullPath: '/impuestos'
      preLoaderRoute: typeof ImpuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  AprenderRoute: AprenderRoute,
  FacturacionRoute: FacturacionRoute,
  ImpuestosRoute: ImpuestosRoute,
  MovimientosRoute: MovimientosRoute,
  ProductosRoute: ProductosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
